### ISSUE TITLE
res.updateConfiguration() deprecated in API 25

### ISSUE THREAD

**Issue by davidmigloz** [YarikSOffice/lingver#10]
Hello,

I was reviewing the code of the library and I noticed that it's using `res.updateConfiguration()` (deprecated in API 25) for all API versions, instead of using [the approach described in the article](https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758).

https://github.com/YarikSOffice/lingver/blob/083f4e98f43f81d00b33fb62bdc3434ccbfcc0b5/library/src/main/java/com/yariksoffice/lingver/Lingver.kt#L116-L132

**Comment by YarikSOffice** [comment]
Actually, the article contains 2 approaches. I prefer this one since it covers more use cases despite using some deprecated API which are not likely to be removed anytime.

For instance, there is no way to update a locale for `application.context` using the modern approach via `createConfigurationContext`.

**Comment by davidmigloz** [comment]
My bad sorry, I didn't continue reading after "API level 25" section. I've researched a bit more and it makes sense your solution. Thank you very much.
