### ISSUE TITLE
Application language is discarded when opening webview

### ISSUE THREAD

**Issue by dima-zemingo** [YarikSOffice/lingver#13]
When having single activity application (but it's not a must) and forcing locale change, when entering a fragment/activity with webview, the language is changed to the default .
This is the case described in stack overflow post - https://stackoverflow.com/questions/40398528/android-webview-language-changes-abruptly-on-android-7-0-and-above/40480347#40480347
It would be nice to add it to your project

**Comment by YarikSOffice** [comment]
Hi @dima-zemingo !
Thanks for the contribution. I'll investigate that and check what I can do. Stay tuned.

**Comment by YarikSOffice** [comment]
Thanks again for your contribution!

Finally, I've investigated the issue. However, I decided to not include the fix in the library itself since I was not able to find an easy solution which could solve this issue for everyone. 

I was thinking of creating a fake webview during the library initialization and setting the desired locale back to prevent this issue from happening in the future. But after some testing I realized that this approach is pretty expensive. 
Eventually, it's up to developers to decide how to deal with it according to their needs and use case.

You can find an example of implementation in the sample app.
