### ISSUE TITLE
Android 5.1.1 language change not working

### ISSUE THREAD

**Issue by lurbenk** [YarikSOffice/lingver#25]
Hi, i implemented language change on my app, everything works fine but i received report about problem on Android 5.1, on this version is language change do nothing, just refresh activity and whole content remain in default language.

Does anybody face similar issue ? or this version and lower are not supported ? 
Thanks upfront for any help :)

**Comment by YarikSOffice** [comment]
@lurbenk The library supports all android versions.  

Could you describe your issue in more details?
- how do you refresh your activities?
- do you use app bundles or the webview?
- do you cover all the supported locales with necessary string resources?
- etc

Also, a sample project reproducing the issue is highly appreciated.

**Comment by lurbenk** [comment]
- refreshing activity by :
val refresh = activity!!.intent
        activity!!.finish()
        activity!!.startActivity(refresh)

- no webview in app and app bundle not used
- app has default ENG resources and SK resources
- string resources should be fine, on newst android version running with no problem

as i checked now app is still in english by default also after lang change. same problem also appears on Android 6.0 (tested just on emulator)

**Comment by YarikSOffice** [comment]
Btw, if you use multiple activities, you have to restart all of them (the entire back stack). 

Besides that, I don't see any issues here. Could you provide a sample project, so I can investigate the issue and fix it asap.

**Comment by lurbenk** [comment]
hi, i tried to extract logic related to language change : https://github.com/lurbenk/languageSample
basicly textView in left top croner works as switcher.
Also this test app remain in english all time

**Comment by YarikSOffice** [comment]
Okay, I've checked the sample app. 

As far as I see, the cause of the issue is a wrong locale resolution. Android is not able to link the `sk` locale and the string resources inside `values-sk-rSK` folder.  However, it works on Android 7 and above due to the [new locale resolution strategy](https://developer.android.com/guide/topics/resources/multilingual-support).

You can put your string resources inside `values-sk` folder to solve the issue. If it's not an option for you for some reason, then you have to find another workaround.

**Comment by lurbenk** [comment]
what a terrible mistake on my side, sorry for bothering you with this issue.
But thank you very much for help and very fast response :) wish to have such a great support and help everywhere :)

**Comment by YarikSOffice** [comment]
@lurbenk you are welcome :)
