### ISSUE TITLE
How to change locale without restarting A activity?

### ISSUE THREAD

**Issue by Kolyall** [YarikSOffice/lingver#26]
I have:
- activity A with option "Change Language", activity B opens after click on "Change Language"
- activity B with list of languages, language is changed after click on element of list by:
```
 val localeCode = languageList[index]
 Lingver.getInstance().setLocale(activity.application, localeCode)
 activity.finish()/*finish activity B*/
```
[result]: Activity A resumed, but locale was not changed

The same behaviour is implemented at Telegram app

**Comment by YarikSOffice** [comment]
Hi @Kolyall 

After changing the locale, you need to refresh the content that was already loaded. In your example, you need to refresh the activity A by either restarting or implementing some custom approach.

As far as I know, Telegram uses Views rather than activities to represent a screen. I suppose they just recreate/reload the view underneath of the screen B.
